_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 1
                - 55
                - 105
            "2":
                - 1
                - 55
                - 105
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.4
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": darwin-arm64
batch_size:
    value: 32
epochs:
    value: 50
learning_rate:
    value: 0.001
patient:
    value: 3
