_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 1
                - 2
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.8
            "8":
                - 3
                - 5
            "12": 0.19.8
            "13": windows-amd64
batch_size:
    value: 8
epochs:
    value: 30
learning_rate:
    value: 0.005
patient:
    value: 3
train_data_size:
    value: 800
val_data_size:
    value: 64
